USE SQLLEARNING;
CREATE TABLE cust(
user_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL 
);

SELECT * FROM SQLLEARNING.cust;
